import type { WorkspaceTransaction } from '@beecount/api-client'
import { Card, CardContent, CardDescription, CardHeader, CardTitle, Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@beecount/ui'
import { CalendarDays } from 'lucide-react'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { analyzeSeanMonthlyComparison } from './analyzeSeanMonthlyComparison'

type Props = { transactions: WorkspaceTransaction[]; currency: string; loading: boolean; error: boolean }
function money(value: number, currency: string) { try { return new Intl.NumberFormat(undefined, { style: 'currency', currency, maximumFractionDigits: 2 }).format(value) } catch { return `${currency} ${value.toFixed(2)}` } }

function Chart({ rows, currency }: { rows: ReturnType<typeof analyzeSeanMonthlyComparison>; currency: string }) {
  const data = rows.filter((row) => row.income || row.expense)
  if (data.length < 2) return null
  return <Card><CardHeader><CardTitle>收支趋势图</CardTitle><CardDescription>收入、支出和净结余统一以曲线显示；鼠标移动到图上可查看月份金额。</CardDescription></CardHeader><CardContent><div className="mb-3 flex gap-4 text-xs"><span className="text-income">● 收入</span><span className="text-expense">● 支出</span><span className="text-primary">● 净结余</span></div><div className="h-60"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false} /><XAxis dataKey="month" tickFormatter={(month) => month.slice(5)} /><YAxis width={44} tickFormatter={(value) => value >= 10000 ? `${(value / 10000).toFixed(1)}万` : value.toFixed(0)} /><Tooltip labelFormatter={(label) => `月份：${label}`} formatter={((value: number, name: string) => [`${name === '支出' ? '-' : name === '收入' ? '+' : ''}${money(value, currency)}`, name]) as never} contentStyle={{ background: 'hsl(var(--popover))', border: '1px solid hsl(var(--border))', borderRadius: 6 }} /><Line type="monotone" dataKey="income" name="收入" stroke="rgb(var(--income-rgb))" strokeWidth={2.5} dot={{ r: 3 }} /><Line type="monotone" dataKey="expense" name="支出" stroke="rgb(var(--expense-rgb))" strokeWidth={2.5} dot={{ r: 3 }} /><Line type="monotone" dataKey="balance" name="净结余" stroke="hsl(var(--primary))" strokeWidth={2.5} dot={{ r: 3 }} /></LineChart></ResponsiveContainer></div></CardContent></Card>
}

export function SeanMonthlyComparisonPanel({ transactions, currency, loading, error }: Props) {
  const rows = analyzeSeanMonthlyComparison(transactions); const visible = rows.filter((row) => row.income || row.expense).reverse()
  return <div className="space-y-5"><div><h1 className="text-2xl font-bold tracking-tight">月度对比</h1><p className="mt-1 text-sm text-muted-foreground">近 12 个自然月的收入、支出和净结余。</p></div>{error ? <Card><CardContent className="py-8 text-destructive">月度数据加载失败。</CardContent></Card> : null}<Chart rows={rows} currency={currency} /><Card><CardHeader><CardTitle className="flex items-center gap-2"><CalendarDays className="h-5 w-5 text-primary" />近 12 个月收支对比</CardTitle><CardDescription>最新月份优先显示；收支均为 0 的月份已隐藏。</CardDescription></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>月份</TableHead><TableHead className="text-right">收入</TableHead><TableHead className="text-right">收入环比</TableHead><TableHead className="text-right">支出</TableHead><TableHead className="text-right">支出环比</TableHead><TableHead className="text-right">净结余</TableHead><TableHead className="text-right">笔数</TableHead></TableRow></TableHeader><TableBody>{visible.map((row) => <TableRow key={row.month}><TableCell>{row.month}</TableCell><TableCell className="text-right text-income">+{money(row.income, currency)}</TableCell><TableCell className="text-right">{row.incomeChange === null ? '—' : `${(row.incomeChange * 100).toFixed(1)}%`}</TableCell><TableCell className="text-right text-expense">-{money(row.expense, currency)}</TableCell><TableCell className="text-right">{row.expenseChange === null ? '—' : `${(row.expenseChange * 100).toFixed(1)}%`}</TableCell><TableCell className={`text-right ${row.balance >= 0 ? 'text-income' : 'text-expense'}`}>{row.balance >= 0 ? '+' : ''}{money(row.balance, currency)}</TableCell><TableCell className="text-right">{row.count}</TableCell></TableRow>)}</TableBody></Table></div>{loading ? <p className="p-4 text-sm text-muted-foreground">正在刷新数据…</p> : null}</CardContent></Card></div>
}
