import { useMemo, useState } from 'react'
import type { WorkspaceTransaction } from '@beecount/api-client'
import { Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@beecount/ui'
import { AlertTriangle, CircleAlert, SearchCheck, ShieldCheck } from 'lucide-react'
import { detectTransactionAnomalies, type TransactionAnomaly } from './detectTransactionAnomalies'

type Props = { transactions: WorkspaceTransaction[]; currency: string; loading: boolean; error: boolean; onRefresh: () => void }
function amountOf(tx: WorkspaceTransaction) { return Math.abs(Number(tx.native_amount ?? tx.amount) || 0) }
function money(value: number, currency: string) { try { return new Intl.NumberFormat(undefined, { style: 'currency', currency, maximumFractionDigits: 2 }).format(value) } catch { return `${currency} ${value.toFixed(2)}` } }
const labels = { 'duplicate': '同日重复', 'rapid-repeat': '短时重复', 'amount-spike': '金额突增', 'price-increase': '疑似涨价', 'missing-info': '信息缺失' }

export function SeanAnomalyDetectionPanel({ transactions, currency, loading, error, onRefresh }: Props) {
  const anomalies = useMemo(() => detectTransactionAnomalies(transactions), [transactions])
  const [severity, setSeverity] = useState<'all' | 'high' | 'medium' | 'low'>('all')
  const [selected, setSelected] = useState<TransactionAnomaly | null>(null)
  const visible = severity === 'all' ? anomalies : anomalies.filter((row) => row.severity === severity)
  const counts = { high: anomalies.filter((row) => row.severity === 'high').length, medium: anomalies.filter((row) => row.severity === 'medium').length, low: anomalies.filter((row) => row.severity === 'low').length }
  return <div className="mx-auto min-w-0 max-w-[1440px] space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold tracking-tight">异常交易检测</h1><p className="mt-1 text-sm text-muted-foreground">发现可能重复、异常涨价或信息不完整的交易。</p></div><Button variant="outline" onClick={onRefresh} disabled={loading}>刷新检测</Button></div>
    {error ? <Card><CardContent className="py-8 text-sm text-destructive">交易数据加载失败。</CardContent></Card> : null}
    <div className="grid gap-3 sm:grid-cols-3"><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">高风险</p><p className="mt-1 text-2xl font-semibold text-expense">{counts.high}</p><p className="text-xs text-muted-foreground">优先检查疑似重复</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">需关注</p><p className="mt-1 text-2xl font-semibold text-amber-500">{counts.medium}</p><p className="text-xs text-muted-foreground">金额异常或信息缺失</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">低风险提示</p><p className="mt-1 text-2xl font-semibold text-primary">{counts.low}</p><p className="text-xs text-muted-foreground">可能发生周期涨价</p></CardContent></Card></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><SearchCheck className="h-5 w-5 text-primary"/>检测结果</CardTitle><CardDescription>异常只代表“值得核对”，不代表交易一定错误。</CardDescription><div className="flex flex-wrap gap-2 pt-2">{([['all', '全部'], ['high', '高风险'], ['medium', '需关注'], ['low', '低风险']] as const).map(([key, label]) => <Button key={key} size="sm" variant={severity === key ? 'default' : 'outline'} onClick={() => setSeverity(key)}>{label}</Button>)}</div></CardHeader><CardContent>{loading ? <p className="py-8 text-sm text-muted-foreground">正在检测交易…</p> : visible.length ? <div className="divide-y divide-border/70">{visible.map((item) => { const income = item.transaction.tx_type === 'income'; return <button key={item.id} type="button" onClick={() => setSelected(item)} className="flex w-full min-w-0 items-start gap-3 py-4 text-left hover:bg-muted/30"><span className={`mt-0.5 rounded-full p-2 ${item.severity === 'high' ? 'bg-expense/10 text-expense' : item.severity === 'medium' ? 'bg-amber-500/10 text-amber-500' : 'bg-primary/10 text-primary'}`}>{item.severity === 'high' ? <AlertTriangle className="h-4 w-4"/> : <CircleAlert className="h-4 w-4"/>}</span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><b>{item.title}</b><Badge variant="secondary">{labels[item.kind]}</Badge></span><span className="mt-1 block text-sm text-muted-foreground">{item.transaction.happened_at.slice(0, 10)} · {item.transaction.note || item.transaction.category_name || '未命名交易'} · {item.reason}</span></span><span className={`shrink-0 font-mono font-semibold ${income ? 'text-income' : 'text-expense'}`}>{income ? '+' : '-'}{money(amountOf(item.transaction), currency)}</span></button> })}</div> : <div className="py-10 text-center"><ShieldCheck className="mx-auto h-9 w-9 text-income"/><p className="mt-3 font-medium">当前没有发现此级别的异常</p><p className="mt-1 text-sm text-muted-foreground">检测结果会随交易记录变化。</p></div>}</CardContent></Card>
    <p className="text-xs text-muted-foreground">本页只读，不会自动删除、修改金额或重新分类。请结合实际情况判断。</p>
    <Dialog open={Boolean(selected)} onOpenChange={(open) => { if (!open) setSelected(null) }}><DialogContent className="max-h-[80vh] max-w-xl overflow-y-auto"><DialogHeader><DialogTitle>{selected?.title || '异常详情'}</DialogTitle><DialogDescription>{selected?.reason}</DialogDescription></DialogHeader>{selected ? <div className="space-y-3"><TransactionRow title="当前交易" tx={selected.transaction} currency={currency}/>{selected.related.map((tx, index) => <TransactionRow key={tx.id} title={`对比记录 ${index + 1}`} tx={tx} currency={currency}/>)}</div> : null}</DialogContent></Dialog>
  </div>
}

function TransactionRow({ title, tx, currency }: { title: string; tx: WorkspaceTransaction; currency: string }) {
  return <div className="rounded-lg border p-3"><p className="text-xs font-medium text-muted-foreground">{title}</p><div className="mt-2 flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-medium">{tx.note || tx.category_name || '未命名交易'}</p><p className="mt-1 text-xs text-muted-foreground">{tx.happened_at.replace('T', ' ').slice(0, 16)} · {tx.category_name || '未分类'} · {tx.account_name || tx.from_account_name || '未设置账户'}</p></div><span className="shrink-0 font-mono font-semibold">{money(amountOf(tx), currency)}</span></div></div>
}
