import { useMemo, useState } from 'react'
import type { WorkspaceAccount, WorkspaceTransaction } from '@beecount/api-client'
import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input, Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@beecount/ui'
import { Calculator, CheckCircle2, Search, TriangleAlert } from 'lucide-react'
import { findReconciliationClues, isReconciliableAccount, reconciliationAccountBalance, transactionTouchesAccount } from './reconciliation'

type Props = { accounts: WorkspaceAccount[]; transactions: WorkspaceTransaction[]; loading: boolean; error: boolean; onRefresh: () => void; onOpenTransactions: (query: string) => void; onAddTransaction: () => void }
function money(value: number, currency: string) { try { return new Intl.NumberFormat(undefined, { style: 'currency', currency, maximumFractionDigits: 2 }).format(value) } catch { return `${currency} ${value.toFixed(2)}` } }

export function SeanAccountReconciliationPanel({ accounts, transactions, loading, error, onRefresh, onOpenTransactions, onAddTransaction }: Props) {
  const candidates = useMemo(() => accounts.filter(isReconciliableAccount).sort((a, b) => a.name.localeCompare(b.name)), [accounts])
  const [accountId, setAccountId] = useState('')
  const [actualText, setActualText] = useState('')
  const [days, setDays] = useState<30 | 60 | 90>(30)
  const selected = candidates.find((row) => row.id === accountId) || candidates[0] || null
  const actual = actualText.trim() === '' ? null : Number(actualText)
  const book = selected ? reconciliationAccountBalance(selected) : 0
  const difference = actual !== null && Number.isFinite(actual) ? actual - book : null
  const cutoff = new Date(); cutoff.setDate(cutoff.getDate() - days)
  const recent = selected ? transactions.filter((tx) => transactionTouchesAccount(tx, selected) && new Date(tx.happened_at) >= cutoff) : []
  const clues = selected && difference !== null ? findReconciliationClues(recent, selected, difference) : []
  const currency = (selected?.currency || 'CNY').toUpperCase()
  const selectAccount = (value: string) => { setAccountId(value); setActualText('') }
  return <div className="mx-auto min-w-0 max-w-[1440px] space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold tracking-tight">账户对账</h1><p className="mt-1 text-sm text-muted-foreground">比较账本余额与银行或支付平台的真实余额，辅助查找差额。</p></div><Button variant="outline" onClick={onRefresh} disabled={loading}>重新读取余额</Button></div>
    {error ? <Card><CardContent className="py-8 text-sm text-destructive">账户或交易数据加载失败。</CardContent></Card> : null}
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Calculator className="h-5 w-5 text-primary"/>开始对账</CardTitle><CardDescription>实际余额只在当前页面使用，不会保存或覆盖账户余额。</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><label className="space-y-2"><span className="text-sm font-medium">选择账户</span><Select value={selected?.id || ''} onValueChange={selectAccount}><SelectTrigger><SelectValue placeholder="请选择账户"/></SelectTrigger><SelectContent>{candidates.map((account) => <SelectItem key={account.id} value={account.id}>{account.name} · {money(reconciliationAccountBalance(account), (account.currency || 'CNY').toUpperCase())}</SelectItem>)}</SelectContent></Select></label><label className="space-y-2"><span className="text-sm font-medium">银行或平台实际余额</span><Input inputMode="decimal" type="number" step="0.01" value={actualText} onChange={(event) => setActualText(event.target.value)} placeholder="请输入当前看到的真实余额" disabled={!selected}/>{selected?.account_type === 'credit_card' ? <span className="block text-xs text-muted-foreground">信用卡欠款请填写负数，例如欠款 2,400 元填写 -2400。</span> : null}</label></CardContent></Card>
    {selected ? <div className="grid gap-3 sm:grid-cols-3"><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">账本余额</p><p className="mt-1 font-mono text-xl font-semibold">{money(book, currency)}</p></CardContent></Card><Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">实际余额</p><p className="mt-1 font-mono text-xl font-semibold">{actual === null || !Number.isFinite(actual) ? '—' : money(actual, currency)}</p></CardContent></Card><Card className={difference === null || Math.abs(difference) < 0.005 ? '' : 'border-expense/30'}><CardContent className="p-4"><p className="text-xs text-muted-foreground">对账差额</p><p className={`mt-1 font-mono text-xl font-semibold ${difference !== null && Math.abs(difference) >= 0.005 ? 'text-expense' : 'text-income'}`}>{difference === null ? '—' : `${difference > 0 ? '+' : ''}${money(difference, currency)}`}</p><p className="mt-1 text-xs text-muted-foreground">实际余额 − 账本余额</p></CardContent></Card></div> : null}
    {difference !== null && Math.abs(difference) < 0.005 ? <Card className="border-income/30 bg-income/5"><CardContent className="flex items-center gap-3 py-5"><CheckCircle2 className="h-6 w-6 text-income"/><div><p className="font-medium">本次账户已经对平</p><p className="text-sm text-muted-foreground">账本余额与输入的实际余额一致。</p></div></CardContent></Card> : null}
    {difference !== null && Math.abs(difference) >= 0.005 ? <><Card className="border-amber-500/30 bg-amber-500/5"><CardContent className="flex gap-3 py-4 text-sm"><TriangleAlert className="h-5 w-5 shrink-0 text-amber-500"/><span>{difference < 0 ? '账本余额偏高，可能存在漏记支出、多记收入或账户选择错误。' : '账本余额偏低，可能存在漏记收入、多记支出或账户选择错误。'}以下结果只是查找线索，需要人工确认。</span></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Search className="h-5 w-5 text-primary"/>可能相关</CardTitle><CardDescription>在最近 {days} 天交易中查找单笔、两笔组合和疑似重复记录。</CardDescription><div className="flex flex-wrap gap-2 pt-2">{([30, 60, 90] as const).map((value) => <Button key={value} size="sm" variant={days === value ? 'default' : 'outline'} onClick={() => setDays(value)}>近 {value} 天</Button>)}</div></CardHeader><CardContent>{clues.length ? <div className="divide-y divide-border/70">{clues.map((clue) => <div key={clue.id} className="py-4"><p className="font-medium">{clue.title}</p><p className="mt-1 text-sm text-muted-foreground">{clue.reason}</p><div className="mt-2 space-y-1">{clue.transactions.map((tx) => <button key={tx.id} type="button" onClick={() => onOpenTransactions(tx.note || tx.category_name || '')} className="flex w-full min-w-0 items-center justify-between gap-3 rounded-md bg-muted/30 px-3 py-2 text-left text-sm hover:bg-muted/60"><span className="min-w-0 truncate">{tx.happened_at.slice(0, 10)} · {tx.note || tx.category_name || '未命名交易'}</span><span className="shrink-0 font-mono">{money(Math.abs(Number(tx.native_amount ?? tx.amount) || 0), currency)}</span></button>)}</div></div>)}</div> : <p className="py-8 text-center text-sm text-muted-foreground">没有找到金额接近的交易线索。差额也可能来自漏记交易、期初余额或手续费。</p>}</CardContent></Card></> : null}
    <Card><CardContent className="flex flex-wrap items-center gap-3 py-4"><span className="min-w-0 flex-1 basis-[220px] text-sm text-muted-foreground">发现问题后，请通过官方交易功能补记或修改；本页不会直接调整余额。</span><Button variant="outline" onClick={() => onOpenTransactions(selected?.name || '')} disabled={!selected}>查看账户交易</Button><Button onClick={onAddTransaction} disabled={!selected}>补记交易</Button></CardContent></Card>
  </div>
}
