import { useState } from 'react'
import type { WorkspaceTransaction } from '@beecount/api-client'
import { Card, CardContent, CardDescription, CardHeader, CardTitle, Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@beecount/ui'
import { ArrowRight, Repeat2 } from 'lucide-react'
import { analyzeTransferFlows, type SeanTransferFlow } from './analyzeTransferFlows'

function money(value: number, currency: string): string { try { return new Intl.NumberFormat(undefined, { style: 'currency', currency, maximumFractionDigits: 2 }).format(value) } catch { return `${currency} ${value.toFixed(2)}` } }
function amountOf(tx: WorkspaceTransaction): number { return Math.abs(Number(tx.amount) || 0) }

export function TransferFlowCard({ transactions, currency }: { transactions: WorkspaceTransaction[]; currency: string }) {
  const report = analyzeTransferFlows(transactions)
  const [selected, setSelected] = useState<SeanTransferFlow | null>(null)
  return <><Card className="xl:col-span-2"><CardHeader><CardTitle className="flex items-center gap-2"><Repeat2 className="h-5 w-5 text-primary" />转账流向</CardTitle><CardDescription>账户之间的资金调拨，不计入收入、支出、净结余或预算。</CardDescription></CardHeader><CardContent><div className="mb-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border bg-muted/20 p-3"><p className="text-xs text-muted-foreground">转账总额</p><p className="mt-1 font-mono text-lg font-semibold">{money(report.total, currency)}</p></div><div className="rounded-xl border bg-muted/20 p-3"><p className="text-xs text-muted-foreground">转账笔数</p><p className="mt-1 font-mono text-lg font-semibold">{report.count}</p></div><div className="rounded-xl border bg-muted/20 p-3"><p className="text-xs text-muted-foreground">最大单笔</p><p className="mt-1 font-mono text-lg font-semibold">{report.largest ? money(amountOf(report.largest), currency) : '—'}</p></div></div>{report.flows.length ? <div className="divide-y divide-border/70">{report.flows.slice(0, 8).map((flow) => <button key={flow.key} type="button" onClick={() => setSelected(flow)} className="flex w-full items-center gap-3 py-3 text-left hover:bg-muted/40"><span className="min-w-0 flex-1"><span className="flex items-center gap-2 text-sm font-medium"><span className="truncate">{flow.from}</span><ArrowRight className="h-3.5 w-3.5 shrink-0 text-muted-foreground"/><span className="truncate">{flow.to}</span></span><span className="mt-1 block text-xs text-muted-foreground">{flow.count} 笔 · 最近 {flow.latestAt.slice(0, 10)}</span></span><span className="shrink-0 font-mono text-sm font-semibold">{money(flow.amount, currency)}</span></button>)}</div> : <p className="py-6 text-sm text-muted-foreground">当前时间范围内没有转账记录。</p>}</CardContent></Card><Dialog open={Boolean(selected)} onOpenChange={(open) => { if (!open) setSelected(null) }}><DialogContent className="max-h-[80vh] max-w-xl overflow-y-auto"><DialogHeader><DialogTitle>{selected ? `${selected.from} → ${selected.to}` : '转账明细'}</DialogTitle><DialogDescription>内部资金调拨明细，不影响收支统计。</DialogDescription></DialogHeader><div className="divide-y divide-border/70">{selected?.transactions.slice().sort((a, b) => b.happened_at.localeCompare(a.happened_at)).map((tx) => <div key={tx.id} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-medium">{tx.note || '账户间转账'}</p><p className="mt-1 text-xs text-muted-foreground">{tx.happened_at.slice(0, 10)}</p></div><span className="font-mono font-semibold">{money(amountOf(tx), currency)}</span></div>)}</div></DialogContent></Dialog></>
}
