import type { NetWorthHistory } from '@beecount/api-client'
import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle } from '@beecount/ui'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { buildSeanAssetTrendRows } from './assetTrend'

type Props = { history: NetWorthHistory | null; currency: string; loading: boolean; error: boolean; onRefresh: () => void }
function money(value: number, currency: string) { try { return new Intl.NumberFormat(undefined, { style: 'currency', currency, maximumFractionDigits: 2 }).format(value) } catch { return `${currency} ${value.toFixed(2)}` } }
function change(value: number | null, currency: string, inverse = false) { if (value === null) return '—'; const positive = inverse ? value <= 0 : value >= 0; return <span className={positive ? 'text-income' : 'text-expense'}>{value >= 0 ? '+' : ''}{money(value, currency)}</span> }

function Chart({ history, currency }: { history: NetWorthHistory | null; currency: string }) {
  const data = (history?.series ?? []).slice(-12).map((row) => ({ ...row, liabilitiesAbsolute: Math.abs(row.liabilities) }))
  if (data.length < 2) return null
  return <Card><CardHeader><CardTitle>资产趋势图</CardTitle><CardDescription>净资产、资产、负债统一以曲线显示；鼠标移动到图上可查看月份金额。</CardDescription></CardHeader><CardContent><div className="mb-3 flex gap-4 text-xs"><span className="text-primary">● 净资产</span><span className="text-income">● 资产</span><span className="text-expense">● 负债</span></div><div className="h-60"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false} /><XAxis dataKey="bucket" tickFormatter={(bucket) => bucket.slice(5)} /><YAxis width={44} tickFormatter={(value) => value >= 10000 ? `${(value / 10000).toFixed(1)}万` : value.toFixed(0)} /><Tooltip labelFormatter={(label) => `月份：${label}`} formatter={((value: number, name: string) => [`${name === '负债' ? '-' : ''}${money(value, currency)}`, name]) as never} contentStyle={{ background: 'hsl(var(--popover))', border: '1px solid hsl(var(--border))', borderRadius: 6 }} /><Line type="monotone" dataKey="net_worth" name="净资产" stroke="hsl(var(--primary))" strokeWidth={2.5} dot={{ r: 3 }} /><Line type="monotone" dataKey="assets" name="资产" stroke="rgb(var(--income-rgb))" strokeWidth={2.5} dot={{ r: 3 }} /><Line type="monotone" dataKey="liabilitiesAbsolute" name="负债" stroke="rgb(var(--expense-rgb))" strokeWidth={2.5} dot={{ r: 3 }} /></LineChart></ResponsiveContainer></div></CardContent></Card>
}

export function SeanAssetTrendsPanel({ history, currency, loading, error, onRefresh }: Props) {
  const rows = buildSeanAssetTrendRows(history); const latest = rows[0]
  return <div className="space-y-5"><div className="flex items-start justify-between gap-3"><div><h1 className="text-2xl font-bold tracking-tight">资产趋势</h1><p className="mt-1 text-sm text-muted-foreground">净资产月度趋势 / 资产负债变化，最多展示最近 12 个月。</p></div><Button variant="outline" onClick={onRefresh} disabled={loading}>刷新数据</Button></div>{error ? <Card><CardContent className="py-8 text-destructive">资产趋势数据加载失败。</CardContent></Card> : null}{latest ? <div className="grid gap-4 md:grid-cols-3"><Card><CardHeader className="pb-2"><CardDescription>净资产</CardDescription><CardTitle className={latest.net_worth >= 0 ? 'text-income' : 'text-expense'}>{money(latest.net_worth, currency)}</CardTitle></CardHeader><CardContent>较上月 {change(latest.netWorthChange, currency)}</CardContent></Card><Card><CardHeader className="pb-2"><CardDescription>资产</CardDescription><CardTitle className="text-income">{money(latest.assets, currency)}</CardTitle></CardHeader><CardContent>较上月 {change(latest.assetsChange, currency)}</CardContent></Card><Card><CardHeader className="pb-2"><CardDescription>负债</CardDescription><CardTitle className="text-expense">-{money(Math.abs(latest.liabilities), currency)}</CardTitle></CardHeader><CardContent>较上月 {change(latest.liabilitiesChange, currency, true)}</CardContent></Card></div> : null}<Chart history={history} currency={currency} /><Card><CardHeader><CardTitle>月度变化</CardTitle><CardDescription>最新月份在最上方。</CardDescription></CardHeader><CardContent>{loading ? <p>正在加载资产历史…</p> : rows.map((row) => <div key={row.bucket} className="grid grid-cols-4 border-b py-3 text-sm"><span>{row.bucket}</span><span className={row.net_worth >= 0 ? 'text-income' : 'text-expense'}>{money(row.net_worth, currency)}</span><span className="text-income">{money(row.assets, currency)}</span><span className="text-expense">-{money(Math.abs(row.liabilities), currency)}</span></div>)}</CardContent></Card></div>
}
