import { useMemo, useState } from 'react'
import type { NetWorthHistory } from '@beecount/api-client'
import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle } from '@beecount/ui'
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

type Props = { history: NetWorthHistory | null; currency: string; loading: boolean; error: boolean; onRefresh: () => void }
type Range = 3 | 6 | 12
function money(value: number, currency: string) { try { return new Intl.NumberFormat(undefined, { style: 'currency', currency, maximumFractionDigits: 2 }).format(value) } catch { return `${currency} ${value.toFixed(2)}` } }

export function SeanAssetTrendsPanel({ history, currency, loading, error, onRefresh }: Props) {
  const [range, setRange] = useState<Range>(12)
  const data = useMemo(() => (history?.series ?? []).slice(-range).map((row) => ({ ...row, liabilitiesAbsolute: Math.abs(row.liabilities) })), [history, range])
  const latest = data[data.length - 1]
  const previous = data[data.length - 2]
  const first = data[0]
  const growth = latest && first && first.net_worth !== 0 ? (latest.net_worth - first.net_worth) / Math.abs(first.net_worth) : null
  const highest = data.length ? data.reduce((best, row) => row.net_worth > best.net_worth ? row : best) : null
  const lowest = data.length ? data.reduce((best, row) => row.net_worth < best.net_worth ? row : best) : null
  const monthChange = latest && previous ? latest.net_worth - previous.net_worth : null
  return <div className="mx-auto max-w-[1440px] space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold tracking-tight">资产趋势</h1><p className="mt-1 text-sm text-muted-foreground">观察净资产长期增长、阶段高点和低点。</p></div><div className="flex flex-wrap gap-2">{([3, 6, 12] as Range[]).map((value) => <Button key={value} size="sm" variant={range === value ? 'default' : 'outline'} onClick={() => setRange(value)}>近 {value} 个月</Button>)}<Button variant="outline" size="sm" onClick={onRefresh} disabled={loading}>刷新数据</Button></div></div>
    {error ? <Card><CardContent className="py-8 text-destructive">资产趋势数据加载失败。</CardContent></Card> : null}
    {latest ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card><CardHeader className="pb-2"><CardDescription>当前净资产</CardDescription><CardTitle className={latest.net_worth >= 0 ? 'text-income' : 'text-expense'}>{money(latest.net_worth, currency)}</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">较上月 <span className={monthChange === null || monthChange >= 0 ? 'text-income' : 'text-expense'}>{monthChange === null ? '—' : `${monthChange >= 0 ? '+' : ''}${money(monthChange, currency)}`}</span></CardContent></Card><Card><CardHeader className="pb-2"><CardDescription>{range} 个月净资产增长率</CardDescription><CardTitle className={growth === null || growth >= 0 ? 'text-income' : 'text-expense'}>{growth === null ? '—' : `${growth >= 0 ? '+' : ''}${(growth * 100).toFixed(1)}%`}</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">以所选范围首月为基准</CardContent></Card><Card><CardHeader className="pb-2"><CardDescription>阶段最高点 · {highest?.bucket}</CardDescription><CardTitle className="text-income">{highest ? money(highest.net_worth, currency) : '—'}</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">所选时间范围内</CardContent></Card><Card><CardHeader className="pb-2"><CardDescription>阶段最低点 · {lowest?.bucket}</CardDescription><CardTitle className={lowest && lowest.net_worth < 0 ? 'text-expense' : ''}>{lowest ? money(lowest.net_worth, currency) : '—'}</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">所选时间范围内</CardContent></Card></div> : null}
    {data.length >= 2 ? <Card><CardHeader><CardTitle>长期资产趋势</CardTitle><CardDescription>净资产、资产和负债按所选范围展示。</CardDescription></CardHeader><CardContent><div className="mb-3 flex gap-4 text-xs"><span className="text-primary">● 净资产</span><span className="text-income">● 资产</span><span className="text-expense">● 负债</span></div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false}/><XAxis dataKey="bucket" tickFormatter={(bucket) => bucket.slice(5)}/><YAxis width={52} tickFormatter={(value) => value >= 10000 ? `${(value / 10000).toFixed(1)}万` : value.toFixed(0)}/><Tooltip labelFormatter={(label) => `月份：${label}`} formatter={((value: number, name: string) => [`${name === '负债' ? '-' : ''}${money(value, currency)}`, name]) as never}/><Line type="monotone" dataKey="net_worth" name="净资产" stroke="hsl(var(--primary))" strokeWidth={2.5}/><Line type="monotone" dataKey="assets" name="资产" stroke="rgb(var(--income-rgb))" strokeWidth={2.5}/><Line type="monotone" dataKey="liabilitiesAbsolute" name="负债" stroke="rgb(var(--expense-rgb))" strokeWidth={2.5}/></LineChart></ResponsiveContainer></div></CardContent></Card> : null}
    <Card><CardHeader><CardTitle>月度变化</CardTitle><CardDescription>最新月份在最上方，仅显示所选范围。</CardDescription></CardHeader><CardContent>{loading ? <p className="text-sm text-muted-foreground">正在加载资产历史…</p> : [...data].reverse().map((row) => <div key={row.bucket} className="grid grid-cols-4 gap-3 border-b py-3 text-sm"><span>{row.bucket}</span><span className={row.net_worth >= 0 ? 'text-income' : 'text-expense'}>{money(row.net_worth, currency)}</span><span className="text-income">{money(row.assets, currency)}</span><span className="text-expense">-{money(Math.abs(row.liabilities), currency)}</span></div>)}</CardContent></Card>
  </div>
}
